# Generated by Django 4.2.7 on 2023-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cudnadieta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorieentry',
            name='kalorie',
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='aktywnosc',
            field=models.CharField(choices=[('niska', 'Niska'), ('umiarkowana', 'Umiarkowana'), ('wysoka', 'Wysoka')], default='niska', max_length=20),
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='waga',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='wiek',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='wzrost',
            field=models.FloatField(default=170),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
