# Generated by Django 4.2.7 on 2023-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cudnadieta', '0002_remove_calorieentry_kalorie_calorieentry_aktywnosc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieentry',
            name='cel',
            field=models.CharField(choices=[('schudnac', 'Schudnąć'), ('utrzymanie', 'Utrzymać wagę'), ('przytyc', 'Przytyć')], default='utrzymanie', max_length=20),
        ),
        migrations.AddField(
            model_name='calorieentry',
            name='plec',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M', max_length=1),
        ),
    ]
